version: '3.8'

services:
    mosquitto:
        image: eclipse-mosquitto
        container_name: mosquitto
        hostname: mosquitto
        ports:
            - 1883:1883
            - 8883:8883
            - 9001:9001
        volumes:
            - ./config:/mosquitto/config
            - ./data:/mosquitto/data
        networks:
            - mosquitto
networks:
    mosquitto:
        name: mosquitto
        driver: bridge
