services:
  mosquitto:
    
    image: eclipse-mosquitto
    volumes:
      - type: bind
        source: ./config/
        target: /srv/mosquitto/config/
      - type: bind
        source: ./log/
        target: /srv/mosquitto/log/
      - type: volume
        source: data
        target: /srv/mosquitto/data/
    ports:
      - target: 1883
        published: 1883
        protocol: tcp
        mode: host
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host

volumes:
  data:
    name: "mqtt-broker-data"
