FROM python:3.9 
# Or any preferred Python version.
ADD simple-sensor.py .
RUN pip install paho-mqtt
CMD python ./simple-sensor.py -b mosquitto -v -i 20 
# Or enter the name of your unique directory and parameter set