version: '3.8'

services:
    mqttsensor:
      build:
        context: .
        dockerfile: dockerfile
      container_name: mqtt-sensor
      hostname: sensor
      networks:
        - mosquitto
networks:
    mosquitto:
        name: mosquitto
        driver: bridge