################################################################################
# Node-RED Stack or Compose
################################################################################
# docker stack deploy node-red --compose-file docker-compose-node-red.yml
# docker-compose -f docker-compose-node-red.yml -p myNoderedProject up
################################################################################
version: "3.7"

services:
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
    networks:
      - node-red-net
      - mosquitto
    volumes:
      - /srv/node-red/data:/data

networks:
  node-red-net:
    name: "node-red"
    external: true
  mosquitto:
        name: mosquitto
        driver: bridge
