services:
  iobroker:
    container_name: iobroker
    image: buanet/iobroker
    hostname: iobroker
    restart: always
    volumes:
      - ./config:/opt/iobroker
    ports:
      - "8081:8081"
      - "8082:8082"
    networks:
      - mosquitto
      - iobroker-net
networks:
   mosquitto:
      name: mosquitto
      driver: bridge
   iobroker-net:
     name: iobroker
     external: true