version: '3.8'
services:
  influxdb:
    image: influxdb
    container_name: influxdb
    hostname: influxdb
    restart: unless-stopped
    volumes:
      - "./data:/var/lib/influxdb2"
    ports:
      - 8086:8086
    networks:
      - node-red-net
      - mosquitto

  telegraf:
    image: telegraf
    hostname: telegraf
    container_name: telegraf
    volumes:
    - ./telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
      - 8125:8125/udp
    networks:
      - node-red-net
      - mosquitto


networks:
  node-red-net:
    name: node-red
    external: true
  mosquitto:
        name: mosquitto
        driver: bridge

